# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c99ff9eab1212194e43b0b5365de8aa9b53f6b83269f0221e0ffc5e629dafcf8f92972f829bbbbb739bd57bbd9badfa3631f2b9b56a248e22627beee1489448

test:
  secret_key_base: 9fabfbe70761519ab20a775edea0c7d019ad60e21797a0941015cf839fce1011be6e57f812b061eb2d3037661660ee55ba8c4ae900f35c3abbfdd939e9e99186

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 9fabfbe70761519ab20a775edea0c7d019ad60e21797a0941015cf839fce1011be6e57f812b061eb2d3037661660ee55ba8c4ae900f35c3abbfdd939e9e99caf
  # secret_key_base: <%= ENV["SECRET_KEY_BASE_DOGS"] %>
